'use client';

/**
 * The document viewer (design/DocViewer.dc.html, DESIGN.md §5.5): tab strip of open documents, document row
 * (kind, name, language, source, Ask about this document, Download) and the body for xlsx / pdf / docx,
 * with loading and failed states. Rendered by <ViewerLayout> in split, full-screen or phone-sheet mode.
 */
import { useEffect, useState } from 'react';
import { api } from '@/lib/client';
import { KIND, LangTag, MONO, fmtMoney, fmtWhen, kindLabel, kindOf } from '../ui';
import { docKey, type DocRef, type Jump, type ViewerMode } from './types';
import type { DocViewerState } from './useDocViewer';
import { TAG_LABEL, endpoints, extOfName, viewKind } from './viewerApi';
import { Broken } from './parts';
import { SheetView } from './SheetView';
import { PdfView } from './PdfView';
import { DocxView } from './DocxView';
import s from './Viewer.module.css';

interface DocMeta { language?: string | null; subtitle?: string; currency?: string | null; total?: number | null }

/** Language, source line and (for generated estimates) currency + total, fetched when a document is first shown. */
function useDocMeta(doc: DocRef | null): [Record<string, DocMeta>, (key: string, m: DocMeta) => void] {
  const [meta, setMeta] = useState<Record<string, DocMeta>>({});
  const key = doc ? docKey(doc) : '';
  useEffect(() => {
    if (!doc) return;
    const ep = endpoints(doc).meta;
    if (!ep) return;
    let off = false;
    api<{ document?: Record<string, any>; file?: Record<string, any> }>(ep).then((r) => {
      if (off) return;
      let m: DocMeta = {};
      if (r.document) m = docMetaFrom(r.document);
      else if (r.file) m = { language: r.file.language ?? null, subtitle: `Knowledge base · ${TAG_LABEL[r.file.tag] ?? 'Other'}` };
      setMeta((all) => ({ ...all, [key]: m }));
    }).catch(() => {});
    return () => { off = true; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [key]);
  return [meta, (k, m) => setMeta((all) => ({ ...all, [k]: { ...all[k], ...m } }))];
}

/** Kind label + colours: documents are workbooks; unknown extensions show their own name in grey. */
function kindOfDoc(d: DocRef): [string, string, string] {
  if (d.source === 'document') return KIND.xlsx;
  const k = viewKind(d);
  if (k === 'unsupported') return [(extOfName(d.name) || 'FILE').toUpperCase().slice(0, 4), 'var(--ink2)', 'var(--sunk)'];
  return [kindLabel(d.name), KIND[kindOf(d.name)][1], KIND[kindOf(d.name)][2]];
}

function docMetaFrom(d: Record<string, any>): DocMeta {
  const t = d.totals?.total;
  return {
    language: d.language ?? null,
    subtitle: `Generated by the agent · ${fmtWhen(d.created_at)}`,
    currency: d.currency ?? null,
    total: typeof t === 'number' ? t : t != null && Number.isFinite(Number(t)) ? Number(t) : null,
  };
}

export function DocViewer({ viewer, mode, onAsk, backLabel = 'Back' }: { viewer: DocViewerState; mode: ViewerMode; onAsk?: (doc: DocRef) => void; backLabel?: string }) {
  const doc = viewer.docs.find((d) => docKey(d) === viewer.activeKey) ?? null;
  const [metas, patchMeta] = useDocMeta(doc);
  const isSheet = mode === 'sheet';
  if (!doc) return null;

  const ep = endpoints(doc);
  const [kLabel, kFg, kBg] = kindOfDoc(doc);
  const meta = metas[docKey(doc)] ?? {};
  const lang = doc.language ?? meta.language;
  const subtitle = doc.subtitle ?? meta.subtitle ?? (doc.source === 'upload' ? 'Attached to this conversation' : doc.source === 'file' ? 'Knowledge base' : 'Generated by the agent');
  const open = (d: DocRef, j?: Jump) => viewer.open(d, j);
  const jump = viewer.jump;
  const ghost = { height: 30, padding: '0 10px', border: 0, borderRadius: 6, background: 'transparent', color: 'var(--ink2)', font: 'inherit', fontSize: 12.5, cursor: 'pointer' } as const;

  /** Every open tab keeps its view mounted (hidden when inactive), so switching tabs keeps sheet, scroll and find. */
  const bodyOf = (d: DocRef) => {
    const k = docKey(d), active = k === viewer.activeKey, m = metas[k] ?? {}, e = endpoints(d), kind = viewKind(d);
    const dl = d.language ?? m.language;
    if (kind === 'xlsx') {
      return (
        <SheetView doc={d} lang={dl} isEstimate={d.source === 'document'} isSheet={isSheet} jump={active ? jump : null} jumpSeq={viewer.jumpSeq}
          total={d.source === 'document' && m.total != null ? { label: 'Estimate total', value: fmtMoney(m.total, m.currency ?? undefined) } : null}
          currency={m.currency} onOpenDoc={open} onEdited={(x) => { const n = docMetaFrom(x); patchMeta(k, { total: n.total, ...(n.currency ? { currency: n.currency } : {}) }); }} />
      );
    }
    if (kind === 'pdf') return <PdfView src={e.raw} download={e.download} isSheet={isSheet} />;
    if (kind === 'docx') return <DocxView src={e.html} download={e.download} isSheet={isSheet} />;
    const ext = extOfName(d.name);
    return <Broken reason={`${ext ? `.${ext} files` : 'Files of this type'} can't be shown in the viewer. Download the original to open it.`} download={e.download} />;
  };

  return (
    <div style={{ height: '100%', width: '100%', minWidth: 0, display: 'flex', flexDirection: 'column', background: 'var(--panel)', color: 'var(--ink)', fontSize: 13, lineHeight: 1.45, position: 'relative', overflow: 'hidden' }}>
      {isSheet ? (
        <div style={{ height: 52, flex: 'none', display: 'flex', alignItems: 'center', gap: 8, padding: '0 8px', borderBottom: '1px solid var(--line)' }}>
          <button type="button" onClick={viewer.close} style={{ height: 36, padding: '0 10px', border: 0, borderRadius: 8, background: 'transparent', color: 'var(--accInk)', font: 'inherit', fontWeight: 500, cursor: 'pointer' }}>‹ {backLabel}</button>
          <div style={{ flex: 1 }} />
          <a href={ep.download} download style={{ height: 36, display: 'inline-flex', alignItems: 'center', padding: '0 10px', borderRadius: 8, textDecoration: 'none', color: 'var(--ink2)' }}>Download</a>
        </div>
      ) : (
        <div style={{ height: 44, flex: 'none', display: 'flex', alignItems: 'flex-end', gap: 2, padding: '0 8px 0 10px', borderBottom: '1px solid var(--line)', background: 'var(--side)' }}>
          <div role="tablist" aria-label="Open documents" style={{ flex: 1, minWidth: 0, display: 'flex', alignItems: 'flex-end', gap: 2, overflow: 'hidden' }}>
            {viewer.docs.map((d) => {
              const k = docKey(d), on = k === viewer.activeKey;
              return (
                <div key={k} role="tab" aria-selected={on} tabIndex={0} onClick={() => viewer.select(k)} onKeyDown={(e) => { if (e.key === 'Enter') viewer.select(k); }} title={d.name}
                  style={{ display: 'flex', alignItems: 'center', gap: 7, height: 36, maxWidth: 220, minWidth: 0, padding: '0 6px 0 12px', borderRadius: '8px 8px 0 0', background: on ? 'var(--panel)' : 'transparent', borderTop: `1px solid ${on ? 'var(--line)' : 'transparent'}`, borderLeft: `1px solid ${on ? 'var(--line)' : 'transparent'}`, borderRight: `1px solid ${on ? 'var(--line)' : 'transparent'}`, borderBottom: 0, marginBottom: -1, cursor: 'pointer', color: on ? 'var(--ink)' : 'var(--ink2)' }}>
                  <span style={{ fontFamily: MONO, fontSize: 9.5, fontWeight: 600, color: kindOfDoc(d)[1], flex: 'none' }}>{kindOfDoc(d)[0]}</span>
                  <span style={{ whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', fontSize: 12.5 }}>{d.name}</span>
                  <button type="button" title="Close tab" aria-label={`Close ${d.name}`} className={s.tabClose} onClick={(e) => { e.stopPropagation(); viewer.closeTab(k); }}
                    style={{ width: 22, height: 22, flex: 'none', border: 0, borderRadius: 5, background: 'transparent', color: 'var(--ink3)', fontSize: 14, lineHeight: 1, cursor: 'pointer' }}>×</button>
                </div>
              );
            })}
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 4, height: 43 }}>
            <button type="button" className={s.ghost} style={ghost} onClick={() => viewer.setMode(mode === 'full' ? 'split' : 'full')}>{mode === 'full' ? 'Exit full screen' : 'Full screen'}</button>
            <button type="button" className={s.ghost} title="Close document" aria-label="Close document" onClick={viewer.close}
              style={{ width: 30, height: 30, border: 0, borderRadius: 6, background: 'transparent', color: 'var(--ink2)', fontSize: 18, lineHeight: 1, cursor: 'pointer' }}>×</button>
          </div>
        </div>
      )}

      <div style={{ flex: 'none', display: 'flex', alignItems: 'center', gap: 12, padding: '12px 16px', borderBottom: '1px solid var(--line)', flexWrap: 'wrap' }}>
        <div style={{ width: 34, height: 40, flex: 'none', borderRadius: 6, background: kBg, color: kFg, display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: MONO, fontSize: 9.5, fontWeight: 600 }}>{kLabel}</div>
        <div style={{ flex: 1, minWidth: 160, display: 'flex', flexDirection: 'column', gap: 2 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, minWidth: 0 }}>
            <span style={{ fontWeight: 600, fontSize: 14, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }} title={doc.name}>{doc.name}</span>
            <LangTag lang={lang} />
          </div>
          <span style={{ fontSize: 12, color: 'var(--ink3)' }}>{subtitle}</span>
        </div>
        <div style={{ display: 'flex', gap: 6 }}>
          {onAsk && (
            <button type="button" className={s.ghost} onClick={() => onAsk(doc)}
              style={{ height: 32, padding: '0 12px', border: '1px solid var(--line)', borderRadius: 8, background: 'var(--panel)', color: 'var(--ink)', font: 'inherit', fontSize: 12.5, fontWeight: 500, cursor: 'pointer' }}>Ask about this document</button>
          )}
          {!isSheet && (
            <a href={ep.download} download style={{ height: 32, display: 'inline-flex', alignItems: 'center', padding: '0 12px', borderRadius: 8, background: 'var(--acc)', color: '#fff', textDecoration: 'none', fontSize: 12.5, fontWeight: 600 }}>Download</a>
          )}
        </div>
      </div>

      {viewer.docs.map((d) => {
        const k = docKey(d);
        return (
          <div key={k} style={{ flex: 1, minHeight: 0, display: k === viewer.activeKey ? 'flex' : 'none', flexDirection: 'column', position: 'relative' }}>
            {bodyOf(d)}
          </div>
        );
      })}
    </div>
  );
}
