/**
 * Document viewer contract (design/DocViewer.dc.html, DESIGN.md §5.5). Pages hold viewer state with
 * useDocViewer() and wrap their content in <ViewerLayout>, which renders the split / full / phone-sheet frame.
 */
export type DocSource = 'document' | 'file' | 'upload';

export interface DocRef {
  /** 'document' = agent output (documents table), 'file' = knowledge file, 'upload' = chat attachment. */
  source: DocSource;
  id: string;
  name: string;
  language?: string | null;
  /** Subtitle, e.g. "Generated by the agent · today 10:45" or "Knowledge base · Hourly norms". */
  subtitle?: string;
}

export interface Jump { sheet?: string; row?: number }

export type ViewerMode = 'split' | 'full' | 'sheet';

export const docKey = (d: Pick<DocRef, 'source' | 'id'>) => `${d.source}:${d.id}`;
